###
POST http://127.0.0.1:8000/api/auth/signup
Content-Type: application/json

{
    "method" : "phone",
    "phone_number" : "+1234567111"
}
###
###
POST http://13.60.171.74:8000/api/auth/signup
Content-Type: application/json

{
    "method" : "phone",
    "phone_number" : "+9187665226311"
}
###
POST http://127.0.0.1:8000/api/auth/verify-otp
Content-Type: application/json

{
  "otp": "1234",
  "phone_number": "+1234567111"
}






###
POST http://13.60.171.74:8000/api/auth/signup
Content-Type: application/json

{
    "method" : "email",
    "email" : "test77@gmail.com",
    "password" : "123456"
}


###

###
# Signup Request
POST http://13.60.171.74:8000/api/auth/signup_create_user
Content-Type: application/json

{
  "name": "Jhon Doe 5",
  "username" : "jhondoeusername",
  "email": "test77@gmail.com",
  "gender" : "male",
  "phone_number" : "+122890802",
  "date_of_birth": "1999-08-24",
  "profile_picture": "default-avatar"
}

###
POST http://127.0.0.1:8000/api/auth/signup_create_user
Content-Type: application/json

{
  "method" : "phone_number",
  "name": "Jhon Doe 9",
  "gender" : "male",
  "email": "jhonedoe9@gmail.com",
  "password" : "+1234567111",
  "phone_number" : "+1234567111",
  "date_of_birth": "1999-08-24",
  "profile_picture": "default-avatar"
}

###
POST http://127.0.0.1:8000//api/auth/signup_create_user
Content-Type: application/json

{
  "method" : "email",
  "name": "Jhon Doe 5",
  "username" : "test77@gmail.com",
  "gender" : "male",
  "email": "test77@gmail.com",
  "password" : "123456789",
  "phone_number" : "+987654321",
  "date_of_birth": "1999-08-24",
  "profile_picture": "default-avatar"
}

### a8d0b0c2be0a5a25151a919e2c4f64cc4fb9139d
# LOGIN REQUEST
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "method": "phone",
  "phone_number": "+1234567890"
}

## 063cb4a5f6817261c3dcb9467e362cb20f67d975 Jhon Doe 
###
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "method": "email",
  "email": "test77@gmail.com",
  "password" : "123456789"
}

### 8eb4ab832c3a27bd103c169420f52543648832e2
POST http://127.0.0.1:8000/api/auth/verify-otp
Content-Type: application/json

{
  "otp": "1234",
  "phone_number": "+1234567890"
}



###

GET http://13.60.171.74:8000/api/auth/test_token
Authorization: Token  5f25a72f95824de8404d79f331a5e020bd69e003


### 25a7f0bca206b050c59d0f5b5ce1dce5cb63d6e1


#PROFILE MANGEMENT 
    # path('profile/view', CustomerProfileView.as_view(), name='view-profile'),
    # path('profile/update', CustomerProfileUpdateView.as_view(), name='update-profile'),
    # path('profile/delete', CustomerProfileDeleteView.as_view(), name='delete-profile')
#View - send the token 
GET http://13.60.171.74:8000/api/profile/view
Content-Type: application/json
Authorization: Token 5f25a72f95824de8404d79f331a5e020bd69e003

###
GET http://127.0.0.1:8000/api/profile/view
Content-Type: application/json
Authorization: Token 5f25a72f95824de8404d79f331a5e020bd69e003

###
#Update 
#specific field
PATCH  http://127.0.0.1:8000/api/profile/update
Content-Type: application/json
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

{
    "name": "Updated  YGB"
}

###
#all details 
PUT http://127.0.0.1:8000/api/profile/update
Content-Type: application/json
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

{
    "name": "Updated  name -2",
    "email" : "yashbav24@gmail.com",
    "phone_number" : "+12345678", 
  "date_of_birth": "2004-08-24",
}

###
#DELETE 

DELETE http://127.0.0.1:8000/api/profile/delete  
Content-Type: application/json
Authorization: Token 54c1d914b81eedfbd31db023c5e63383d22aa968



### 19.096042531572127, 72.83127903395128
# 19.2764581,72.8730165
#Location
GET http://127.0.0.1:8000/api/salons?latitude=19.2764581&longitude=72.8730165
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#Services 

#Sample Create Services 

POST http://127.0.0.1:8000/api/salons/1/create_service
Content-Type: application/json

{
    "service_name": "Haircut",
    "service_type": "Basic",
    "duration_in_mins": 30,
    "price": 500,
    "category": 1,
    "rating": 4.5,
    "service_image": "path/to/image.jpg"
}

###

GET http://127.0.0.1:8000/api/services/filter?category=Hair&priceMin=500&priceMax=1500&rating=4.5
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#Salon details

GET http://127.0.0.1:8000/api/salons/1
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/featured-salons/
Content-Type: application/json

### BOOKMARKS
### CREATE BOOKMARK
POST http://127.0.0.1:8000//api/bookmarks
Content-Type: application/json
Authorization: Token 5f25a72f95824de8404d79f331a5e020bd69e003

{
  "salon_id" : 3
}

###
### DELETE BOOKMARK
DELETE http://127.0.0.1:8000//api/bookmarks
Content-Type: application/json
Authorization: Token 5f25a72f95824de8404d79f331a5e020bd69e003

{
  "salon_id" : 1
}

###
#Service detials
POST http://127.0.0.1:8000/api/service_categories
Content-Type: application/json

{
    "business": 1,  
    "name": "Hair Services",
    "description": "All hair-related services",
    "parent": null
}


###
#Service Filters 
GET http://127.0.0.1:8000/api/salons/filter/?category=Haircut
Content-Type: application/json


###
GET http://127.0.0.1:8000/api/salons/1/services
Content-Type: application/json



###
#BOOKING 
POST http://127.0.0.1:8000/api/bookings/create
Content-Type: application/json
Authorization: Token 5f25a72f95824de8404d79f331a5e020bd69e003

{
  "salon_id": 1,
  "service_id": 1,
  "appointment_date": "2025-01-24T10:00:00Z"
}

###
#Booking get 

GET http://127.0.0.1:8000/api/bookings/status
Authorization: Token 5f25a72f95824de8404d79f331a5e020bd69e003

###
#Booking Cancel 
DELETE http://127.0.0.1:8000/api/bookings/1/cancel
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#View Booking Status 
GET http://127.0.0.1:8000/api/bookings/status?userId=3
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###


GET http://127.0.0.1:8000/api/all_bookings




###

#Coupons 
POST http://13.60.171.74:8000/api/coupons/
Content-Type: application/json

{
    "name": "THRIFTY100",
    "description": "Flat 100 off Friday booking!",
    "discount_price": null,
    "discount_percentage": 10.0,
    "valid_from": "2025-01-01T00:00:00Z",
    "valid_to": "2025-02-01T23:59:59Z",
    "is_active": true,
    "usage_limit": 100,
    "applicable_services": [],
    "applicable_salon": null
}

###

GET  http://13.60.171.74:8000/api/coupons/
Content-Type: application/json
