###
POST http://127.0.0.1:8000/api/auth/signup
Content-Type: application/json

{
    "method" : "phone",
    "phone_number" : "+9187665226311"
}
###

POST http://127.0.0.1:8000/api/auth/verify-otp
Content-Type: application/json

{
  "otp": "8976",
  "phone_number": "+9187665226311"
}






###
POST http://127.0.0.1:8000/api/auth/signup
Content-Type: application/json

{
    "method" : "email",
    "email" : "yashbav2224@gmail.com",
    "password" : "123456"
}


###

###
# Signup Request
POST http://127.0.0.1:8000/api/auth/signup_create_user
Content-Type: application/json

{
  "unique_id": "AABDHP",
  "name": "YGB",
  "username" : "hks",
  "email": "ygb@gmail.com",
  "phone_number": "+9187665226311",
  "date_of_birth": "2004-08-24",
  "profile_picture": "default-avatar"
}

###
# LOGIN REQUEST
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "method": "phone",
  "phone_number": "+9187665226311"
}


###
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "method": "email",
  "email": "@gmail.com",
  "password" : "123456"
}

###
POST http://127.0.0.1:8000/api/auth/verify-otp
Content-Type: application/json

{
  "otp": "2805",
  "phone_number": "+9187665226311"
}



###

GET http://127.0.0.1:8000/api/auth/test_token
Authorization: Token  ca1988d0df616f396f1b858c2dca82bc1ab9d792


###


#PROFILE MANGEMENT 
    # path('profile/view', CustomerProfileView.as_view(), name='view-profile'),
    # path('profile/update', CustomerProfileUpdateView.as_view(), name='update-profile'),
    # path('profile/delete', CustomerProfileDeleteView.as_view(), name='delete-profile')
#View - send the token 
GET http://127.0.0.1:8000/api/profile/view
Content-Type: application/json
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###

#Update 
#specific field
PATCH  http://127.0.0.1:8000/api/profile/update
Content-Type: application/json
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

{
    "name": "Updated  YGB"
}

###
#all details 
PUT http://127.0.0.1:8000/api/profile/update
Content-Type: application/json
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

{
    "name": "Updated  name -2",
    "email" : "yashbav24@gmail.com",
    "phone_number" : "+12345678", 
  "date_of_birth": "2004-08-24",
}

###
#DELETE 

DELETE http://127.0.0.1:8000/api/profile/delete  
Content-Type: application/json
Authorization: Token 54c1d914b81eedfbd31db023c5e63383d22aa968



###
#Location
GET http://127.0.0.1:8000/api/salons?latitude=28.6139&longitude=77.2090
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#Services 
GET http://127.0.0.1:8000/api/services/filter?category=Hair&priceMin=500&priceMax=1500&rating=4.5
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#Salon details

GET http://127.0.0.1:8000/api/salons/1
Content-Type: application/json


###
#Service detials
GET http://127.0.0.1:8000/api/salons/1/services
Content-Type: application/json


###
#BOOKING 
POST http://127.0.0.1:8000/api/bookings/create
Content-Type: application/json
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

{
  "salon_id": 1,
  "service_id": 2,
  "appointment_date": "2025-01-24T10:00:00Z"
}

###
#Booking get 

GET http://127.0.0.1:8000/api/bookings/status?userId=2
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#Booking Cancel 
DELETE http://127.0.0.1:8000/api/bookings/1/cancel
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792

###
#View Booking Status 
GET http://127.0.0.1:8000/api/bookings/status?userId=3
Authorization: Token ca1988d0df616f396f1b858c2dca82bc1ab9d792


