# Generated by Django 5.1.4 on 2025-01-22 21:33

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customer_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('salon_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('salon_description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[api.models.validate_image_size])),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_duration_in_mins', models.PositiveIntegerField()),
                ('package_price', models.PositiveIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_packages', to='api.salon')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_categories', to='api.salon')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Add-on', 'Add-on')], max_length=50)),
                ('duration_in_mins', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='services-images/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_services', to='api.salon')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.servicecategory')),
            ],
        ),
    ]
