# Generated by Django 5.1.4 on 2025-01-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_salon_packages_servicecategory_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
