# Generated by Django 5.1.4 on 2025-01-29 06:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='unique_id',
            field=models.CharField(default=api.models.generate_unique_id, max_length=10, unique=True),
        ),
    ]
