# Generated by Django 5.1.4 on 2025-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='address_description',
            field=models.TextField(blank=True),
        ),
    ]
