# Generated by Django 5.1.4 on 2025-02-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_salon_address_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
